### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zaidajani**
Hi,

I have added two more projects which accept hacktober pull requests.

### CODE REVIEW

**Review by vivian-dai — CHANGES_REQUESTED** [review]
The format should be `[authorusername/reponame](link)`. If you also look more carefully at the other topics available, you should be able to sort this better.

**Comment by zaidajani** [comment]
Hi,

The requested changes have been accomplished. 

Thanks.

**Review by vivian-dai — CHANGES_REQUESTED** [review]
Change the repo name to the same as the one in the link. Change the capitalization for author's name to match the actual author name.

**Comment by zaidajani** [comment]
Hey,

I have capitalized the names and made them as per the format of others.

**Review by vivian-dai — CHANGES_REQUESTED** [review]
The repository names are not supposed to be capitalized. Just keep the name consistent with the URL.

**Comment by zaidajani** [comment]
hey, 

I have made the changes, but if any more changes are needed, I would like you to send all the rules/formats for it. Thanks.

**Comment by vivian-dai** [comment]
image
The "a" is supposed to be a lowercase. Same for the other repository.

**Comment by zaidajani** [comment]
Thanks for showing the fixings, I have done the same for the other repo as well.

**Review by vivian-dai — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by zaidajani** [comment]
Thanks for merging the pull request. Thanks!

**Pull request merged**
